"""
Command line runner for the Music Recommender Simulation.

This file helps you quickly run and test your recommender.

You will implement the functions in recommender.py:
- load_songs
- score_song
- recommend_songs
"""

from src.recommender import load_songs, recommend_songs

MAIN_OUTPUT_PROMPT = """
With #file:src/main.py as context, format the recommendation output for the terminal in a clean,
readable layout. Display each recommended song's title, final score, and the specific reasons
generated by the scoring function. Keep the result easy to scan in plain text.
""".strip()

SAMPLE_USER_PROFILES = {
    "High-Energy Pop": {"genre": "pop", "mood": "happy", "energy": 0.8},
    "Chill Lofi": {"genre": "lofi", "mood": "chill", "energy": 0.4},
    "Deep Intense Rock": {"genre": "rock", "mood": "intense", "energy": 0.9},
}


def main() -> None:
    songs = load_songs("data/songs.csv")

    # Default example profile for the current CLI run
    profile_name = "High-Energy Pop"
    user_prefs = SAMPLE_USER_PROFILES[profile_name]

    recommendations = recommend_songs(user_prefs, songs, k=5)

    print(f"\nTop recommendations for {profile_name}\n")
    for index, rec in enumerate(recommendations, start=1):
        # You decide the structure of each returned item.
        # A common pattern is: (song, score, explanation)
        song, score, explanation = rec
        print(f"{index}. {song['title']} by {song['artist']}")
        print(f"   Score: {score:.2f}")
        print(f"   Reasons: {explanation}")
        print()


if __name__ == "__main__":
    main()
